# Main configuration file for GNN experiments

# Experiment settings
experiment:
  name: "moe_tuning"
  device: "cuda"
  seeds: [1,2,3]
  hyper_search:
    enable: true
    n_trials_1: 10
    test_after: false

# Dataset configuration
dataset:
  dataset_name: "GOODMotif"
  task_type: "graph_classification"
  path: "./datasets"
  shift_type: "covariate"
  batch_size: 64
  num_workers: 4
  domain: 'basis'

# Model configuration
model:
  type: "moe"
  hidden_dim: 300
  num_layers: 3
  dropout: 0.5
  global_pooling: "mean"
  weight_reg: 1.0
  weight_ce: 1.0
  weight_div: 1.0
  weight_load: 0.5
  num_experts: 8
  aggregation: "weighted_mean"
  rho_edge: 0.7

# Training configuration
training:
  epochs: 50
  lr: 0.001
  weight_decay: 0.0001
  early_stopping:
    patience: 10
    min_delta: 0.001

# Gating module configuration
gate:
  activation: "entmax"
  entmax_alpha: 1.38
  train_after: 10
  finetune_epochs: 0